### PR TITLE
Add Kubernetes platform context fields

### PR DESCRIPTION
**Pull request by ghost**
Adds the `context.platform.kubernetes` property to the schema which contains
properties related to Kubernetes Pods.

### CODE REVIEW

**Comment by DavidAntaramian** [comment]
Your changes look good, but Ben is responsible for approval on this project. I've assigned him for review

**Comment by binarylogic** [comment]
@carkmorwin and I talked offline, we cannot support arrays and decided to capture the root (top level) owner only for this first version.

**Review by binarylogic — COMMENTED** [review]
Looks good. In regards to the `root_owner` document what exactly is type? And would someone need to use both fields to execute a search on that? I'm thinking about facets and how those will work.

**Comment by ghost** [comment]
@binarylogic It would look like the following:

```json
{
  "root_owner": {
    "kind": "Deployment", 
    "name": "my-app"
  }
}
```

**Comment by ghost** [comment]
I anticipate searching would be on either field or both, but not sure. I think that will be clearer when people are actually sending data.

Really the goal here is for searching app logs, which are mostly likely going to be under a deployment. 

Show me logs where root_owner is `my-app-v1` or something like that. 

---

I don't want to call it App, or it's hard to make assumptions on what the thing will actually be. But down the road maybe we want to say, if we see that root_owner is a deployment, then place it under an app facet. Not sure how realistic that is on the front end.

**Comment by binarylogic** [comment]
That makes sense. Can you squash the commits and add a changelog entry? Once that's done this is good to merge.

**Comment by ghost** [comment]
@binarylogic done, but can you give it one final pass before merge?

**Comment by binarylogic** [comment]
Looks good, :shipit:

**Pull request merged**
